import { useEffect, useMemo, useState } from 'react'
import { Eye, FilePlus2, ImagePlus, Rocket, Save, ShieldCheck, Trash2 } from 'lucide-react'
import { createAvgGame, deleteAvgGameDraft, deleteAvgMediaAsset, importAvgMediaAsset, loadAvgAuthoringSnapshot, publishAvgGame, seedAvgAcceptanceGame, updateAvgPresentation, validateAvgGame, type AvgAuthoringSnapshot } from '../../lib/avg/authoring'
import { applyAvgCue, EMPTY_AVG_STAGE, freezeAvgMediaAsset, parseAvgPresentationContent } from '../../lib/avg/runtime'
import type { AvgMediaKind, WorkspaceScope } from '../../lib/types'
import { AVG_MEDIA_KINDS } from '../../lib/types'
import { useDomainT } from '../../i18n'
import { AVG_MEDIA_KIND_LABEL_KEYS, projectCanonicalLabel } from '../../i18n/display-projection'
import { useDialog } from '../shared/Dialog'

const EMPTY: AvgAuthoringSnapshot = { definitions: [], modules: [], nodes: [], beats: [], choices: [], presentationModules: [], assets: [], releases: [] }
export default function AvgGameWorkbench({ scope }: { scope: WorkspaceScope }) {
  const dialog = useDialog()
  const { t } = useDomainT('simulation')
  const [snapshot, setSnapshot] = useState(EMPTY); const [selected, setSelected] = useState<number | null>(null); const [content, setContent] = useState('{"version":1,"cues":[]}')
  const [kind, setKind] = useState<AvgMediaKind>('background'); const [assetKey, setAssetKey] = useState(''); const [alt, setAlt] = useState(''); const [source, setSource] = useState('作者本地导入' /* 持久数据：写入媒资 source 字段，不随 UI locale 投影 */); const [license, setLicense] = useState(''); const [files, setFiles] = useState<File[]>([]); const [previewBeatKey, setPreviewBeatKey] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  const refresh = async (wanted?: number | null) => { const next = await loadAvgAuthoringSnapshot(scope); setSnapshot(next); const id = wanted ?? selected ?? next.definitions[0]?.id ?? null; setSelected(id); setContent(next.presentationModules.find(row => row.gameDefinitionId === id)?.contentJson ?? '{"version":1,"cues":[]}') }
  useEffect(() => { void refresh() }, [scope.projectId, scope.worldId, scope.workId]) // eslint-disable-line react-hooks/exhaustive-deps
  const run = async (fn: () => Promise<void>) => { setError(''); try { await fn() } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)) } }
  const definition = snapshot.definitions.find(item => item.id === selected)
  const beats = useMemo(() => snapshot.beats.filter(item => item.moduleId === definition?.narrativeModuleId).sort((a, b) => a.order - b.order), [definition?.narrativeModuleId, snapshot.beats])
  const timeline = useMemo(() => { try { return parseAvgPresentationContent(content) } catch { return null } }, [content])
  const latestAssets = useMemo(() => snapshot.assets.filter((asset, index, rows) => rows.findIndex(item => item.assetKey === asset.assetKey) === index).map(freezeAvgMediaAsset), [snapshot.assets])
  const previewStage = useMemo(() => {
    let stage = structuredClone(EMPTY_AVG_STAGE)
    const cues = (timeline?.cues ?? []).filter(cue => cue.beatKey === previewBeatKey).sort((a, b) => a.order - b.order)
    for (const cue of cues) stage = applyAvgCue(stage, cue, latestAssets, {})
    return stage
  }, [latestAssets, previewBeatKey, timeline])
  const totalBytes = snapshot.assets.reduce((sum, asset) => sum + asset.byteSize, 0)
  const slug = (value: string) => value.toLowerCase().replace(/\.[^.]+$/, '').replace(/[^a-z0-9._:-]+/g, '-').replace(/^-+|-+$/g, '') || 'asset'
  return <div className="avg-workbench" data-testid="avg-workbench"><aside><h3>{t('textGame.avg.workbench.projectsHeading')}</h3>{snapshot.definitions.map(def => <button className={def.id === selected ? 'active' : ''} key={def.id} onClick={() => { setSelected(def.id!); setContent(snapshot.presentationModules.find(row => row.gameDefinitionId === def.id)?.contentJson ?? '') }}>{def.title}</button>)}<button onClick={() => void run(async () => { const row = await createAvgGame({ scope }); await refresh(row.id) })}><FilePlus2 />{t('textGame.avg.workbench.create')}</button><button onClick={() => void run(async () => { const row = await seedAvgAcceptanceGame({ scope }); await refresh(row.id); setMessage(t('textGame.avg.workbench.sampleLoadedMessage')) })}><Eye />{t('textGame.avg.workbench.loadSample')}</button></aside>
    <main><header><div><h2>{t('textGame.avg.workbench.title')}</h2><p>{t('textGame.avg.workbench.intro')}</p></div>{selected && <><button onClick={() => void run(async () => { const report = await validateAvgGame(scope, selected); setMessage(`${report.valid ? t('textGame.avg.workbench.checkPassed') : t('textGame.avg.workbench.checkFailed')} · ${[...report.errors, ...report.warnings].join('；') || t('textGame.avg.workbench.noIssues')}`) })}><ShieldCheck />{t('textGame.avg.workbench.check')}</button><button onClick={() => void run(async () => { const published = await publishAvgGame({ scope, gameDefinitionId: selected }); setMessage(t('textGame.avg.workbench.publishedMessage', { version: published.gameRelease.version })); await refresh(selected) })}><Rocket />{t('textGame.avg.workbench.publish')}</button><button className="danger" onClick={() => void run(async () => { const confirmed = await dialog.confirm({ title: t('textGame.avg.workbench.deleteConfirmTitle'), message: t('textGame.avg.workbench.deleteConfirmMessage'), confirmText: t('textGame.avg.workbench.deleteConfirmAction'), tone: 'danger' }); if (!confirmed) return; await deleteAvgGameDraft({ scope, gameDefinitionId: selected }); await refresh(null) })}><Trash2 />{t('textGame.avg.workbench.deleteDraft')}</button></>}</header>
      {error && <div role="alert">{error}</div>}{message && <div className="avg-message">{message}</div>}
      <section className="avg-author-grid"><article><h3>{t('textGame.avg.workbench.mediaLibraryHeading')}</h3><p>{t('textGame.avg.workbench.mediaLibraryStats', { versions: snapshot.assets.length, size: (totalBytes / 1024 / 1024).toFixed(2) })}</p><label>{t('textGame.avg.workbench.assetKeyLabel')}<input value={assetKey} onChange={event => setAssetKey(event.target.value)} /></label><label>{t('textGame.avg.workbench.kindLabel')}<select value={kind} onChange={event => setKind(event.target.value as AvgMediaKind)}>{AVG_MEDIA_KINDS.map(value => <option key={value} value={value}>{projectCanonicalLabel(t, AVG_MEDIA_KIND_LABEL_KEYS, value)}</option>)}</select></label><label>{t('textGame.avg.workbench.altTextLabel')}<input value={alt} onChange={event => setAlt(event.target.value)} /></label><label>{t('textGame.avg.workbench.sourceLabel')}<input value={source} onChange={event => setSource(event.target.value)} /></label><label>{t('textGame.avg.workbench.licenseLabel')}<input value={license} onChange={event => setLicense(event.target.value)} /></label><input aria-label={t('textGame.avg.workbench.importFilesAria')} type="file" multiple onChange={event => setFiles(Array.from(event.target.files ?? []))} /><button disabled={files.length === 0 || (files.length === 1 && !assetKey.trim())} onClick={() => void run(async () => { for (const file of files) { const key = files.length === 1 ? assetKey.trim() : `${assetKey.trim() || kind}.${slug(file.name)}`; await importAvgMediaAsset({ scope, assetKey: key, kind, name: file.name, blob: file, altText: alt || (kind.startsWith('character') || ['background', 'cg', 'ui'].includes(kind) ? file.name : ''), source, license }) } setMessage(t('textGame.avg.workbench.importedMessage', { count: files.length })); setFiles([]); await refresh(selected) })}><ImagePlus />{files.length > 1 ? t('textGame.avg.workbench.importBatch', { count: files.length }) : t('textGame.avg.workbench.importSingle')}</button><ul>{snapshot.assets.map(asset => <li key={asset.id}><div><code>{asset.assetKey}@{asset.version}</code><span>{projectCanonicalLabel(t, AVG_MEDIA_KIND_LABEL_KEYS, asset.kind)} · {asset.byteSize} B</span></div><button aria-label={t('textGame.avg.workbench.deleteAssetAria', { asset: `${asset.assetKey}@${asset.version}` })} onClick={() => void run(async () => { const confirmed = await dialog.confirm({ title: t('textGame.avg.workbench.deleteAssetConfirmTitle', { asset: `${asset.assetKey}@${asset.version}` }), message: t('textGame.avg.workbench.deleteAssetConfirmMessage'), confirmText: t('textGame.avg.workbench.deleteAssetConfirmAction'), tone: 'danger' }); if (!confirmed) return; await deleteAvgMediaAsset({ scope, mediaAssetId: asset.id! }); await refresh(selected) })}><Trash2 /></button></li>)}</ul></article>
      <article><h3>{t('textGame.avg.workbench.timelineHeading')}</h3><p>{t('textGame.avg.workbench.timelineIntro')}</p><textarea rows={18} value={content} onChange={event => setContent(event.target.value)} /><button disabled={!selected} onClick={() => void run(async () => { parseAvgPresentationContent(content); await updateAvgPresentation({ scope, gameDefinitionId: selected!, content }); setMessage(t('textGame.avg.workbench.timelineSavedMessage')); await refresh(selected) })}><Save />{t('textGame.avg.workbench.saveTimeline')}</button><div className="avg-cue-preview"><h3>{t('textGame.avg.workbench.previewHeading')}</h3><select aria-label={t('textGame.avg.workbench.previewSelectAria')} value={previewBeatKey} onChange={event => setPreviewBeatKey(event.target.value)}><option value="">{t('textGame.avg.workbench.selectBeatOption')}</option>{beats.map(beat => <option key={beat.beatKey} value={beat.beatKey}>{beat.beatKey} · {beat.text.slice(0, 28)}</option>)}</select>{previewBeatKey && <><p>{t('textGame.avg.workbench.cueCountLine', { count: timeline?.cues.filter(cue => cue.beatKey === previewBeatKey).length ?? 0 })}</p><dl><dt>{t('textGame.avg.workbench.previewBackground')}</dt><dd>{previewStage.backgroundAssetKey ?? t('textGame.avg.workbench.previewNone')}</dd><dt>{t('textGame.avg.workbench.previewCg')}</dt><dd>{previewStage.cgAssetKey ?? t('textGame.avg.workbench.previewNone')}</dd><dt>{t('textGame.avg.workbench.previewActors')}</dt><dd>{previewStage.actors.map(actor => `${actor.actorKey}:${actor.assetKey}@${actor.slot}`).join(' · ') || t('textGame.avg.workbench.previewNone')}</dd><dt>{t('textGame.avg.workbench.previewAudio')}</dt><dd>{previewStage.activeAudio.map(audio => `${audio.channel}:${audio.assetKey}`).join(' · ') || t('textGame.avg.workbench.previewNone')}</dd><dt>{t('textGame.avg.workbench.previewCamera')}</dt><dd>{previewStage.camera.x}, {previewStage.camera.y}, ×{previewStage.camera.scale}</dd></dl></>}</div></article></section>
    </main></div>
}
